export const CART_PRODUCT = "CARD_PRODUCT"
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const INCREASE_QTY = "INCREASE_QTY"
export const INCREASE_CART_ITEM_QTY = "INCREASE_CART_ITEM_QTY"
export const DECREASE_CART_ITEM_QTY = "DECREASE_CART_ITEM_QTY"



export const GET_ALL_SALES = "GET_ALL_SALES"
export const BIND_SALES_INFO = "BIND_SALES_INFO"